[db]
dsn = "root:@tcp(127.0.0.1:4000)/client_test?charset=utf8mb4&parseTime=true"
idle = 10
open = 10
[cdb]
dsn = "root:123456@tcp(127.0.0.1:3306)/client_test?charset=utf8mb4&parseTime=true"
idle = 10
open = 10
[sql]
fpath = "./config/sql.file"
